import { ddLang } from './localize';
import type { Lang } from './translations';

/**
 * Nette, leesbare namen voor entiteit-domeinen (device-types).
 * Engels is de standaard; Nederlands wordt gekozen op basis van de HA-taal.
 * Onbekende domeinen vallen terug op een "geprettificeerde" naam
 * (underscores → spaties, elk woord met hoofdletter).
 */
const DOMAIN_NAMES: Record<Lang, Record<string, string>> = {
  en: {
    light: 'Lights',
    switch: 'Switches',
    fan: 'Fans',
    cover: 'Covers',
    lock: 'Locks',
    climate: 'Climate',
    media_player: 'Media players',
    camera: 'Cameras',
    person: 'People',
    vacuum: 'Vacuums',
    alarm_control_panel: 'Alarm',
    binary_sensor: 'Binary sensors',
    sensor: 'Sensors',
    energy: 'Energy',
    scene: 'Scenes',
    event: 'Events',
    script: 'Scripts',
    automation: 'Automations',
    button: 'Buttons',
    number: 'Numbers',
    select: 'Selectors',
    input_boolean: 'Toggles',
    input_number: 'Numbers',
    input_select: 'Selectors',
    input_button: 'Buttons',
    input_text: 'Text fields',
    water_heater: 'Water heaters',
    humidifier: 'Humidifiers',
    siren: 'Sirens',
    valve: 'Valves',
    update: 'Updates',
    weather: 'Weather',
    sun: 'Sun',
    device_tracker: 'Device trackers',
    remote: 'Remotes',
    image: 'Images',
    todo: 'To-do lists',
    calendar: 'Calendars',
    lawn_mower: 'Lawn mowers',
    text: 'Text fields',
    date: 'Dates',
    time: 'Times',
    timer: 'Timers',
  },
  nl: {
    light: 'Lampen',
    switch: 'Schakelaars',
    fan: 'Ventilatoren',
    cover: 'Zonwering',
    lock: 'Sloten',
    climate: 'Klimaat',
    media_player: 'Mediaspelers',
    camera: "Camera's",
    person: 'Personen',
    vacuum: 'Stofzuigers',
    alarm_control_panel: 'Alarm',
    binary_sensor: 'Binaire sensoren',
    sensor: 'Sensoren',
    energy: 'Energie',
    scene: 'Scènes',
    event: 'Gebeurtenissen',
    script: 'Scripts',
    automation: 'Automatiseringen',
    button: 'Knoppen',
    number: 'Nummers',
    select: 'Keuzelijsten',
    input_boolean: 'Schakelaars',
    input_number: 'Nummers',
    input_select: 'Keuzelijsten',
    input_button: 'Knoppen',
    input_text: 'Tekstvelden',
    water_heater: 'Boilers',
    humidifier: 'Luchtbevochtigers',
    siren: 'Sirenes',
    valve: 'Kleppen',
    update: 'Updates',
    weather: 'Weer',
    sun: 'Zon',
    device_tracker: 'Apparaatlocatie',
    remote: 'Afstandsbedieningen',
    image: 'Afbeeldingen',
    todo: 'Takenlijsten',
    calendar: "Agenda's",
    lawn_mower: 'Grasmaaiers',
    text: 'Tekstvelden',
    date: 'Datums',
    time: 'Tijden',
    timer: 'Timers',
  },
  'zh-Hant': {
    light: "燈光",
    switch: "開關",
    fan: "風扇",
    cover: "門簾",
    lock: "門鎖",
    climate: "溫控",
    media_player: "媒體播放器",
    camera: "攝影機",
    person: "個人",
    vacuum: "掃地機器人",
    alarm_control_panel: "警戒控制面板",
    binary_sensor: "二進位感測器",
    sensor: "感測器",
    energy: "能源",
    scene: "場景",
    event: "事件",
    script: "腳本",
    automation: "自動化",
    button: "按鈕",
    number: "數字",
    select: "選擇",
    input_boolean: "開關框",
    input_number: "數字",
    input_select: "選擇框",
    input_button: "按鈕",
    input_text: "文字",
    water_heater: "熱水器",
    humidifier: "加濕器",
    siren: "警報",
    valve: "閥門",
    update: "更新",
    weather: "氣象",
    sun: "太陽",
    device_tracker: "裝置追蹤器",
    remote: "遙控器",
    image: "影像",
    todo: "待辦清單",
    calendar: "行事曆",
    lawn_mower: "割草機",
    text: "文字",
    date: "日期",
    time: "時間",
    timer: "計時器",
  },
  'zh-Hans': {
    light: "灯光",
    switch: "开关",
    fan: "风扇",
    cover: "卷帘",
    lock: "锁",
    climate: "空调",
    media_player: "媒体播放器",
    camera: "摄像头",
    person: "人员",
    vacuum: "扫地机",
    alarm_control_panel: "警报控制面板",
    binary_sensor: "二元传感器",
    sensor: "传感器",
    energy: "能源",
    scene: "场景",
    event: "事件",
    script: "脚本",
    automation: "自动化",
    button: "按钮",
    number: "数值输入器",
    select: "选择",
    input_boolean: "输入布尔值",
    input_number: "数值输入器",
    input_select: "输入选择表",
    input_button: "按钮",
    input_text: "文本",
    water_heater: "热水器",
    humidifier: "加湿器",
    siren: "警报器",
    valve: "阀门",
    update: "更新",
    weather: "天气",
    sun: "日出日落",
    device_tracker: "设备跟踪器",
    remote: "遥控",
    image: "图像",
    todo: "待办清单",
    calendar: "行事历",
    lawn_mower: "割草机",
    text: "文本",
    date: "日期",
    time: "时间",
    timer: "计时器",
  },
};

/**
 * Leesbare namen voor (binary_)sensor device-classes, zodat een motion-sensor
 * als "Motion" verschijnt i.p.v. "Binary sensors".
 */
const DEVICE_CLASS_NAMES: Record<Lang, Record<string, string>> = {
  en: {
    motion: 'Motion',
    moving: 'Motion',
    occupancy: 'Occupancy',
    presence: 'Presence',
    door: 'Doors',
    garage_door: 'Garage doors',
    window: 'Windows',
    opening: 'Openings',
    smoke: 'Smoke',
    gas: 'Gas',
    carbon_monoxide: 'Carbon monoxide',
    moisture: 'Moisture',
    safety: 'Safety',
    tamper: 'Tamper',
    vibration: 'Vibration',
    sound: 'Sound',
    lock: 'Locks',
    battery: 'Battery',
    battery_charging: 'Charging',
    connectivity: 'Connectivity',
    power: 'Power',
    plug: 'Plugs',
    problem: 'Problems',
    heat: 'Heat',
    cold: 'Cold',
    light: 'Light',
    running: 'Running',
    update: 'Updates',
    door_lock: 'Locks',
  },
  nl: {
    motion: 'Beweging',
    moving: 'Beweging',
    occupancy: 'Aanwezigheid',
    presence: 'Aanwezigheid',
    door: 'Deuren',
    garage_door: 'Garagedeuren',
    window: 'Ramen',
    opening: 'Openingen',
    smoke: 'Rook',
    gas: 'Gas',
    carbon_monoxide: 'Koolmonoxide',
    moisture: 'Vocht',
    safety: 'Veiligheid',
    tamper: 'Sabotage',
    vibration: 'Trilling',
    sound: 'Geluid',
    lock: 'Sloten',
    battery: 'Batterij',
    battery_charging: 'Opladen',
    connectivity: 'Verbinding',
    power: 'Stroom',
    plug: 'Stekkers',
    problem: 'Problemen',
    heat: 'Hitte',
    cold: 'Kou',
    light: 'Licht',
    running: 'Actief',
    update: 'Updates',
    door_lock: 'Sloten',
  },
  'zh-Hant': {
    motion: "動作",
    moving: "動作",
    occupancy: "佔空",
    presence: "在場",
    door: "門",
    garage_door: "車庫門",
    window: "窗戶",
    opening: "開啟中",
    smoke: "煙霧",
    gas: "瓦斯",
    carbon_monoxide: "一氧化碳",
    moisture: "水氣",
    safety: "安全",
    tamper: "篡改",
    vibration: "震動",
    sound: "聲響",
    lock: "門鎖",
    battery: "電量",
    battery_charging: "充電中",
    connectivity: "連線",
    power: "電力",
    plug: "插座",
    problem: "異常",
    heat: "熱",
    cold: "冷",
    light: "光線",
    running: "執行中",
    update: "更新",
    door_lock: "門鎖",
  },
  'zh-Hans': {
    motion: "运动",
    moving: "动作",
    occupancy: "此处有人",
    presence: "人体存在",
    door: "门",
    garage_door: "车库门",
    window: "窗户",
    opening: "打开",
    smoke: "烟雾",
    gas: "燃气",
    carbon_monoxide: "一氧化碳",
    moisture: "潮度",
    safety: "安全性",
    tamper: "篡改",
    vibration: "振动",
    sound: "声音",
    lock: "锁",
    battery: "电池",
    battery_charging: "充电中",
    connectivity: "连通性",
    power: "电源",
    plug: "插头",
    problem: "问题",
    heat: "过热",
    cold: "过冷",
    light: "光线",
    running: "运行",
    update: "更新",
    door_lock: "锁",
  },
};

/** Leesbare, gelokaliseerde naam voor een device-class. */
export function getDeviceClassName(hass: any, deviceClass: string): string {
  const lang = ddLang(hass);
  return (
    DEVICE_CLASS_NAMES[lang]?.[deviceClass] ??
    DEVICE_CLASS_NAMES.en[deviceClass] ??
    prettifyDomain(deviceClass)
  );
}

/** Maak van een ruw domein ("binary_sensor") een leesbare naam ("Binary Sensor"). */
export function prettifyDomain(domain: string): string {
  return domain
    .split('_')
    .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : w))
    .join(' ');
}

/** Leesbare, gelokaliseerde naam voor een domein. */
export function getDomainName(hass: any, domain: string): string {
  const lang = ddLang(hass);
  return (
    DOMAIN_NAMES[lang]?.[domain] ??
    DOMAIN_NAMES.en[domain] ??
    prettifyDomain(domain)
  );
}
